#! /usr/bin/env bash

while read attr links owner group size month day time filename; do
	cat <<- EOF
			Filename:	$filename
			Size:		$size
			Owner:		$owner
			Group:		$group
			Modified:	$month $day $time
			Links:		$links
			Attributes:	$attr

		EOF
done < <(ls -AFhltrL | tail +2)

