#! /usr/bin/env bash

exit_on_signal_SIGINT() {
	echo "Script interrupted." 2>& 1
	exit 0
}

exit_on_signal_SIGTERM() {
	echo "Script terminated." 2>& 1
	exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

SLEEP_DELAY=5

for i in {1..10}; do
	echo "Iteration $i of 10"
	sleep "$SLEEP_DELAY"
done

