#! /usr/bin/env bash

test_file() {
	declare -r FILE="$1"
	IS_FILE=""
	
	if ! [ -n "$FILE" ]; then
		echo "The file name is empty." >& 2
		return 1
	fi
	
	if ! [ -e "$FILE" ]; then
		echo "$FILE does not exist."
		return 1
	fi
	
	if [ -f "$FILE" ]; then
		echo "$FILE is a regular file."
		IS_FILE=1
	fi
	
	if [ -d "$FILE" ]; then
		echo "$FILE is a directory."
	fi
	
	if [ -r "$FILE" ]; then
		echo "$FILE is readable."
	fi
	
	if [ -w "$FILE" ]; then
		echo "$FILE is writable."
	fi 
	 
	if [ -x "$FILE" ]; then
		if [ -n "$IS_FILE" ]; then
			echo "$FILE is executable."
		else
			echo "$FILE is searchable."
		fi
	fi  
	
	return 0
}

