#! /usr/bin/env bash

file_info() {

	if [ ! -e $1 ]; then
		echo "$FUNCNAME: usage: $FUNCNAME <file_path>" >& 2
		return 1
	fi

	echo -e "\nFile type:"
	file $1

	echo -e "\nFile status:"
	stat $1

}

file_info $1

