#! /usr/bin/env bash

INT=""
read -p "Please, enter an integer -> " INT

if [ -z "$INT" ]; then
	echo "The given integer is absent" >& 2
	exit 1
fi

if ! [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	echo "The given value is not an integer." >& 2
	exit 2
fi

if (($INT == 0));then
	echo "INT is zero."
else
	if (($INT < 0)); then
		echo "INT is negative."
	else
		echo "INT is positive."
	fi

	if ((($INT % 2) == 0)); then
		echo "INT is even."
	else
		echo "INT is odd."
	fi
fi

exit 0

