#! /usr/bin/env bash

read -t 10 -sp "Enter secret passphrase > " secret_pass
exit_code=$(echo $?)

echo

if [ "$exit_code" -eq 0 ]; then
	echo -e "Secret passphrase = '$secret_pass'"
else
	echo "Input timed out" >& 2
	exit 1
fi

