#! /usr/bin/env bash

foo=0

func_1() {
	local foo

	foo=1
	echo "$FUNCNAME: foo = $foo"
}

func_2() {
	local foo

	foo=2
	echo "$FUNCNAME: foo = $foo"
}

echo "global: foo = $foo"
func_1
echo "global: foo = $foo"
func_2
echo "global: foo = $foo"

